fix for rare case where IP-number is changed.
rsl = None  results in:
```
Traceback (most recent call last):
  File "./scannet2.py", line 262, in <module>
    lstOut = lstvssql(lstOut) # compare the list with the database
  File "./scannet2.py", line 79, in lstvssql
    line[1] = "-" + rsl[3]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

This can be caused by a lease on an IP number that has not yet been
released while the MAC-addr has acquired a different IP (due to
predefined hostname; eg. `osmc` does this).